name: Deploy to Cloudflare Workers

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API to Cloudflare Workers

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".tool-versions"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build schema package
        run: pnpm --filter @repo/schema build

      - name: Build API
        run: pnpm --filter api build

      - name: Set Cloudflare Worker secrets
        run: |
          echo "${{ secrets.ALLOWED_DISCORD_SERVER_ID }}" | pnpm wrangler secret put ALLOWED_DISCORD_SERVER_ID --env production
          echo "${{ secrets.BASE_URL }}" | pnpm wrangler secret put BASE_URL --env production
          echo "${{ secrets.FRONTEND_BASE_URL }}" | pnpm wrangler secret put FRONTEND_BASE_URL --env production
          echo "${{ secrets.DATABASE_URL }}" | pnpm wrangler secret put DATABASE_URL --env production
          echo "${{ secrets.DISCORD_CLIENT_ID }}" | pnpm wrangler secret put DISCORD_CLIENT_ID --env production
          echo "${{ secrets.DISCORD_CLIENT_SECRET }}" | pnpm wrangler secret put DISCORD_CLIENT_SECRET --env production
          echo "${{ secrets.S3_BUCKET_NAME }}" | pnpm wrangler secret put S3_BUCKET_NAME --env production
          echo "${{ secrets.S3_ACCOUNT_ID }}" | pnpm wrangler secret put S3_ACCOUNT_ID --env production
          echo "${{ secrets.S3_ACCESS_KEY_ID }}" | pnpm wrangler secret put S3_ACCESS_KEY_ID --env production
          echo "${{ secrets.S3_ACCESS_KEY_SECRET }}" | pnpm wrangler secret put S3_ACCESS_KEY_SECRET --env production
          echo "${{ secrets.S3_FILE_BASE_URL }}" | pnpm wrangler secret put S3_FILE_BASE_URL --env production
        working-directory: "apps/api"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.S3_ACCOUNT_ID }}

      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.S3_ACCOUNT_ID }}
          workingDirectory: "apps/api"
          command: deploy --minify --env production
